/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vpprotype;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;



// ========== TODO
// ========== * Implement Radio Buttons to switch between the table and video view of the
// ==========   scollPane_video_data view viewPortView
//=========== * Toggle the endabled state Save and SaveAs menuItems

public class MainWindow extends javax.swing.JFrame {

    private Double[][]  runData;
    private Object[]    columnHeaders;   
    private JCheckBox[] lineSelections;
    private JComboBox[] colorSelections;
   
// ========== TODO: 
// ========== * Add these instance variables to the data model
    private File        dataFile;       
    private File        videoFile;
// =========
    
    //file we will save our current Run in
    private File saveFile;

    
    private Color[] colors;
    private String currentDirectory;
    
    private DataModel model;
    
    boolean saved; //true if program has been saved and nothing has changed since then, false if there are unsaved changes
    boolean playing; //true if video is currently playing, false if it is paused
        
    public MainWindow() {
        initComponents();
        
        this.setIconImage(new ImageIcon("VB_Logo.png").getImage());
        this.setTitle("Data Visualization");

        initializeLineColors();
        initializeLineSelectors();
        initializeColorSelectors();
        
        // Hides all of the grpah controls until file data is loaded
        panel_graphInputs.setVisible(false);
 
        // Sets the default directory to the DATFile directory in the project folder.
        currentDirectory = "DATFiles\\";
        
        button_backward.setEnabled(false);
        button_forward.setEnabled(false);
        button_end.setEnabled(false);
        button_pause.setEnabled(false);
        button_front.setEnabled(false);
        
        saved = true; //at the beginning of our program, it will have no new changes
        disableSaveMenu(); //no need to save the program until we have made changes

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table_dataTable = new javax.swing.JTable();
        panel_videoPanel = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        panel_graphInputs = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        panel_graphDisplayElements = new javax.swing.JPanel();
        scrollPane_graph = new javax.swing.JScrollPane();
        graphPanel = new GraphPanel();
        button_dataFileChooser = new javax.swing.JButton();
        textField_graphFile = new javax.swing.JTextField();
        label_graphFile = new javax.swing.JLabel();
        slider = new javax.swing.JSlider();
        scrollPane_data_video = new javax.swing.JScrollPane();
        radioButton_data = new javax.swing.JRadioButton();
        radioButton_video = new javax.swing.JRadioButton();
        label_videoFile = new javax.swing.JLabel();
        textField_videoFile = new javax.swing.JTextField();
        button_videoFileChooser = new javax.swing.JButton();
        button_pause = new javax.swing.JButton();
        button_forward = new javax.swing.JButton();
        button_backward = new javax.swing.JButton();
        button_front = new javax.swing.JButton();
        button_end = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menuItem_open = new javax.swing.JMenuItem();
        menuItem_save = new javax.swing.JMenuItem();
        menuItem_saveAs = new javax.swing.JMenuItem();
        menuItem_close = new javax.swing.JMenuItem();

        table_dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        javax.swing.GroupLayout panel_videoPanelLayout = new javax.swing.GroupLayout(panel_videoPanel);
        panel_videoPanel.setLayout(panel_videoPanelLayout);
        panel_videoPanelLayout.setHorizontalGroup(
            panel_videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel_videoPanelLayout.setVerticalGroup(
            panel_videoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("jCheckBox4");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("jCheckBox5");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("jCheckBox6");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("jCheckBox7");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("jCheckBox8");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("jCheckBox9");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        jCheckBox10.setText("jCheckBox10");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("jCheckBox11");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });

        jCheckBox12.setText("jCheckBox12");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox2.setSelectedIndex(2);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox3.setSelectedIndex(3);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox4.setSelectedIndex(4);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox5.setSelectedIndex(5);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox6.setSelectedIndex(6);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox7.setSelectedIndex(7);
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox8.setSelectedIndex(8);
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox9.setSelectedIndex(9);
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox10.setSelectedIndex(1);
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox11.setSelectedIndex(2);
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "green", "magenta", "orange", "pink", "red", "yellow", "light gray" }));
        jComboBox12.setSelectedIndex(3);
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_graphInputsLayout = new javax.swing.GroupLayout(panel_graphInputs);
        panel_graphInputs.setLayout(panel_graphInputsLayout);
        panel_graphInputsLayout.setHorizontalGroup(
            panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_graphInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox6)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox7)
                    .addComponent(jCheckBox8)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5))
                .addGap(20, 20, 20))
        );
        panel_graphInputsLayout.setVerticalGroup(
            panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_graphInputsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5))
                .addGap(3, 3, 3)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_graphInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox12))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        graphPanel.setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        scrollPane_graph.setViewportView(graphPanel);

        button_dataFileChooser.setText("Choose File");
        button_dataFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_dataFileChooserActionPerformed(evt);
            }
        });

        textField_graphFile.setEditable(false);

        label_graphFile.setText("Data File:");

        slider.setValue(0);
        slider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel_graphDisplayElementsLayout = new javax.swing.GroupLayout(panel_graphDisplayElements);
        panel_graphDisplayElements.setLayout(panel_graphDisplayElementsLayout);
        panel_graphDisplayElementsLayout.setHorizontalGroup(
            panel_graphDisplayElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_graphDisplayElementsLayout.createSequentialGroup()
                .addGroup(panel_graphDisplayElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_graphDisplayElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrollPane_graph, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel_graphDisplayElementsLayout.createSequentialGroup()
                            .addComponent(label_graphFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textField_graphFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(button_dataFileChooser)))
                    .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_graphDisplayElementsLayout.setVerticalGroup(
            panel_graphDisplayElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_graphDisplayElementsLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panel_graphDisplayElementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_graphFile)
                    .addComponent(textField_graphFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_dataFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane_graph, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        scrollPane_data_video.setPreferredSize(new java.awt.Dimension(600, 400));

        buttonGroup1.add(radioButton_data);
        radioButton_data.setText("Data");
        radioButton_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_dataActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioButton_video);
        radioButton_video.setText("Video");
        radioButton_video.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButton_videoActionPerformed(evt);
            }
        });

        label_videoFile.setText("Video File:");

        textField_videoFile.setEditable(false);

        button_videoFileChooser.setText("Choose File");
        button_videoFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_videoFileChooserActionPerformed(evt);
            }
        });

        button_pause.setText("| |");
        button_pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_pauseActionPerformed(evt);
            }
        });

        button_forward.setText("forward");
        button_forward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_forwardActionPerformed(evt);
            }
        });

        button_backward.setText("backwards");
        button_backward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_backwardActionPerformed(evt);
            }
        });

        button_front.setText("front");
        button_front.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_frontActionPerformed(evt);
            }
        });

        button_end.setText("end");
        button_end.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_endActionPerformed(evt);
            }
        });

        menu_file.setText("File");

        menuItem_open.setText("Open");
        menuItem_open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_openActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_open);

        menuItem_save.setText("Save");
        menuItem_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_saveActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_save);

        menuItem_saveAs.setText("Save As");
        menuItem_saveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_saveAsActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_saveAs);

        menuItem_close.setText("Close");
        menuItem_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItem_closeActionPerformed(evt);
            }
        });
        menu_file.add(menuItem_close);

        jMenuBar.add(menu_file);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_graphInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panel_graphDisplayElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(label_videoFile)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textField_videoFile, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(button_videoFileChooser))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(radioButton_data)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(radioButton_video)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(button_pause, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_forward, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_backward, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_front, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_end, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(scrollPane_data_video, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(panel_graphInputs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_graphDisplayElements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton_data)
                    .addComponent(radioButton_video))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textField_videoFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_videoFile)
                    .addComponent(button_videoFileChooser))
                .addGap(16, 16, 16)
                .addComponent(scrollPane_data_video, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_forward)
                    .addComponent(button_backward)
                    .addComponent(button_front)
                    .addComponent(button_pause)
                    .addComponent(button_end)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //any time a checkbox is changed or a line color is changed, our program has new unsaved changes
    //set saved to false and enable save menu because we have a reason to save
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        buildGraph();
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox9ActionPerformed
   
    private void sliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderStateChanged
        int slideValue = slider.getValue();       
        ((GraphPanel) graphPanel).setScaleFactor(slideValue);
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_sliderStateChanged
  
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        buildGraph();
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void button_dataFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_dataFileChooserActionPerformed
        
        // create a file chooser object to read files from the currentDirectory
        JFileChooser jfc = new JFileChooser(currentDirectory);
        
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            dataFile = jfc.getSelectedFile();
            loadDataFile(dataFile);
            
            currentDirectory = jfc.getCurrentDirectory().toString();
            
        }
        //after choosing a new file, we have unsaved changes
        saved = false;
        enableSaveMenu();
        
    }//GEN-LAST:event_button_dataFileChooserActionPerformed

    //writed DataModel to savefile
    private void menuItem_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_saveActionPerformed
        try {
            if (saveFile == null){
                //call saveAs and pass in the evt parameter of this method
                //user should now have set a saveFile
                menuItem_saveAsActionPerformed(evt);
                
                //if file is still null, return out
                if (saveFile == null){
                    return;
                }
            }
            
            FileOutputStream fos = new FileOutputStream(saveFile);
            ObjectOutputStream oos = new ObjectOutputStream(fos);

            // Create a data model out of all of the program save data
            if (runData == null)    return;

            boolean[]   lineInputs  = new boolean[lineSelections.length];
            int[]       colorInputs = new int[colorSelections.length];

            for (int i=0; i<lineSelections.length; i++){
                lineInputs[i] = lineSelections[i].isSelected();
                colorInputs[i] = colorSelections[i].getSelectedIndex();
            }

            DataModel model = new DataModel(runData, columnHeaders, lineInputs, colorInputs, videoFile, dataFile);

            oos.writeObject(model);

            oos.close();
            fos.close();
            //we are now saved and have no new changes
            saved = true;
            disableSaveMenu();
              
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "File Not Found", "ERROR: " + ex.toString(), JOptionPane.ERROR_MESSAGE);

        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "IOException", "ERROR: " + ex.toString(), JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_menuItem_saveActionPerformed

    //opens user selected save file and sets all aspects of data to the datamodel contained in the opened file
    private void menuItem_openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_openActionPerformed
        try {
        
            JFileChooser jfc = new JFileChooser(currentDirectory);

            if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                File file = jfc.getSelectedFile();        

                FileInputStream fis = new FileInputStream(file);
                ObjectInputStream ois = new ObjectInputStream(fis);
                
                DataModel model = (DataModel)ois.readObject();
                
                runData = model.getRunData();
                columnHeaders = model.getColumnHeaders();
                videoFile = model.getVideoFile();
                dataFile = model.getDataFile();
                                
                if (dataFile != null){
                    textField_graphFile.setText(dataFile.getAbsolutePath());
                }
                else{
                    textField_graphFile.setText("THERE IS NO DATAFILE SELECTED");
                }
                if (videoFile != null){
                    textField_videoFile.setText(videoFile.getAbsolutePath());
                }
                else{
                    textField_videoFile.setText("THERE IS NO VIDEOFILE SELECTED");
                }
                
                
                // Transfer saved inputs to the checkBoxes and comboBoxes
                
                for (int i=0; i<lineSelections.length; i++) {
                    lineSelections[i].setSelected(model.getLineSelections()[i]);
                    colorSelections[i].setSelectedIndex(model.getColorSelections()[i]);                   
                }

                currentDirectory = jfc.getCurrentDirectory().toString();

                buildGraph();
                panel_graphInputs.setVisible(true);
                 
                ois.close();
                fis.close();
                //after opening a new file, we have no new changes and dont need the save menu
                saved = true;
                disableSaveMenu();
              
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "DataFile Not Found", "ERROR: " + ex.toString(), JOptionPane.ERROR_MESSAGE);

        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "DataFile Not Found", "ERROR: " + ex.toString(), JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Class Not Found", "ERROR: " + ex.toString(), JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_menuItem_openActionPerformed

    //allows user to choose a new videofile
    private void button_videoFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_videoFileChooserActionPerformed

        panel_videoPanel = new VideoPanel();
        //set right viewport to videopanel
        scrollPane_data_video.setViewportView(panel_videoPanel);
        
        //choose video file
        JFileChooser jfc = new JFileChooser(currentDirectory);
        if (jfc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            videoFile = jfc.getSelectedFile();
        }
        
        //set videofile text field to path of video file
        textField_videoFile.setText(videoFile.getAbsolutePath());
        
        //make sure our buttons are turned on and "video settings" are activated
        radioButton_video.doClick();
        
        //start playing video and save this information in our playing boolean
        ((VideoPanel) panel_videoPanel).startVideo(videoFile);
        playing = true;
        
        //we now have unsaved changes
        saved = false;
        enableSaveMenu();
    }//GEN-LAST:event_button_videoFileChooserActionPerformed

    private void menuItem_saveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_saveAsActionPerformed
        //simply change saveFile instance variable to whatever user selects and call save() to save this slsected file
        JFileChooser jfc = new JFileChooser(currentDirectory);
        if (jfc.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) { 
            saveFile = jfc.getSelectedFile();
            menuItem_saveActionPerformed(evt);
        }
    }//GEN-LAST:event_menuItem_saveAsActionPerformed

    //if we have unsaved changes, make the user save
    //if everything is saved, close the program
    private void menuItem_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItem_closeActionPerformed
        if (!saved){
            JOptionPane.showMessageDialog(this, "You have unsaved changes. Would you like to save?", "Are you sure you want to close?", JOptionPane.CLOSED_OPTION);
            menuItem_saveAsActionPerformed(evt);
            saved = true;
        }
        else{ //saved == true, we can safely exit
            System.exit(0);
        }
    }//GEN-LAST:event_menuItem_closeActionPerformed

    //if user wants to display video, enable video buttons and display video
    //if there is no videofile, tell the user to select a video
    private void radioButton_videoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_videoActionPerformed
        if (!(videoFile == null)){
            scrollPane_data_video.setViewportView(panel_videoPanel);
            button_backward.setEnabled(true);
            button_forward.setEnabled(true);
            button_end.setEnabled(true);
            button_pause.setEnabled(true);
            button_front.setEnabled(true);
            textField_videoFile.setText(videoFile.getAbsolutePath());
            ((VideoPanel)panel_videoPanel).startVideo(videoFile);
            playing = true;
        }
        else{
            JOptionPane.showMessageDialog(this, "YOU MUST CHOOSE A VIDEOFILE TO BE DISPLAYED USING THE CHOOSE FILE BUTTON", "ERROR: NO VIDEO FILE FOUND", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_radioButton_videoActionPerformed

    //if user wants to display data, disable video buttons and display data
    //if there is no datafile, tell the user to select a file
    private void radioButton_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButton_dataActionPerformed
        if (!(dataFile == null)){
            // Load the data table with all data
            table_dataTable = new JTable(runData, columnHeaders);
            scrollPane_data_video.setViewportView(table_dataTable);
            scrollPane_data_video.setViewportView(table_dataTable);
            button_backward.setEnabled(false);
            button_forward.setEnabled(false);
            button_end.setEnabled(false);
            button_pause.setEnabled(false);
            button_front.setEnabled(false);
            textField_graphFile.setText(dataFile.getAbsolutePath());
            
            //pause video if there is one
            if (videoFile != null){
                ((VideoPanel)panel_videoPanel).pause();
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this, "YOU MUST CHOOSE A DATAFILE TO BE DISPLAYED USING THE CHOOSE FILE BUTTON", "ERROR: NO DATA FILE FOUND", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_radioButton_dataActionPerformed

    //if video is playing, pause, set playing to false to remember for later, and set text to play
    //if not (video is stopped), play the video, remember that it is playing, and set text to pause
    private void button_pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_pauseActionPerformed
        if (playing){
            ((VideoPanel)panel_videoPanel).pause();
            playing = false;
            button_pause.setText("Play");
        }
        else{
            ((VideoPanel)panel_videoPanel).play();
            playing = true;
            button_pause.setText("||");
        }
    }//GEN-LAST:event_button_pauseActionPerformed

    private void button_forwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_forwardActionPerformed
        ((VideoPanel)panel_videoPanel).forward();
    }//GEN-LAST:event_button_forwardActionPerformed

    private void button_backwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_backwardActionPerformed
        ((VideoPanel)panel_videoPanel).backward();
    }//GEN-LAST:event_button_backwardActionPerformed

    private void button_frontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_frontActionPerformed
        ((VideoPanel) panel_videoPanel).startVideo(videoFile);
        ((VideoPanel)panel_videoPanel).front();
        button_pause.doClick();
        button_pause.setText("Play");
    }//GEN-LAST:event_button_frontActionPerformed

    private void button_endActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_endActionPerformed
        ((VideoPanel)panel_videoPanel).end();
        //set text to play because we automatically pause when we end
        button_pause.doClick();
        button_pause.setText("Play");
    }//GEN-LAST:event_button_endActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_backward;
    private javax.swing.JButton button_dataFileChooser;
    private javax.swing.JButton button_end;
    private javax.swing.JButton button_forward;
    private javax.swing.JButton button_front;
    private javax.swing.JButton button_pause;
    private javax.swing.JButton button_videoFileChooser;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JLabel label_graphFile;
    private javax.swing.JLabel label_videoFile;
    private javax.swing.JMenuItem menuItem_close;
    private javax.swing.JMenuItem menuItem_open;
    private javax.swing.JMenuItem menuItem_save;
    private javax.swing.JMenuItem menuItem_saveAs;
    private javax.swing.JMenu menu_file;
    private javax.swing.JPanel panel_graphDisplayElements;
    private javax.swing.JPanel panel_graphInputs;
    private javax.swing.JPanel panel_videoPanel;
    private javax.swing.JRadioButton radioButton_data;
    private javax.swing.JRadioButton radioButton_video;
    private javax.swing.JScrollPane scrollPane_data_video;
    private javax.swing.JScrollPane scrollPane_graph;
    private javax.swing.JSlider slider;
    private javax.swing.JTable table_dataTable;
    private javax.swing.JTextField textField_graphFile;
    private javax.swing.JTextField textField_videoFile;
    // End of variables declaration//GEN-END:variables

    
    //loads datafile into table and the 2d array using paremeter passed in
    private void loadDataFile(File file) {
        
        try {
            Scanner data = new Scanner(file);
            
            // Load the column headers into a seperate Object array.
            Scanner headers = new Scanner(data.nextLine());
            headers.useDelimiter(",");
            
            // Get headers from data file first, then load to an array
            ArrayList<String> tempHeaders = new ArrayList<>();
            
            while (headers.hasNext()){
                tempHeaders.add(headers.next());
            }
            
            // Convert the tempHeaders list into an Array
            columnHeaders = tempHeaders.toArray();


            // Reads the rest of the data and assigns to a 2D ArrayList.
            // Then writes the data from the 2D ArrayList to the 2D Array
            ArrayList<String> lineArrayList = new ArrayList<>();

            // Adds each line to an ArrayList so that the total number of rows
            // can be calculated for the 2D arry or data
            while (data.hasNextLine()){
                lineArrayList.add(data.nextLine());
            }
            
            // Set up the 2D Array and add data to the array by looping through the
            // ArrayList
            runData = new Double[lineArrayList.size()][columnHeaders.length];
            
            for (int row=0; row<lineArrayList.size(); row++) {
                
                Scanner line = new Scanner(lineArrayList.get(row));
                line.useDelimiter(",");
                
                int column=0;
                
                while (line.hasNext()) {
                    runData[row][column] = Math.abs(Double.parseDouble(line.next()));
                    column++;
                }
    
            }
            
            // AutoPopulate the text for the checkboxes
            for (int i=1; i<columnHeaders.length; i++) {
                lineSelections[i].setText((String)columnHeaders[i]);
            }
            
                       
            // Show the Controls panel so that all of the graph inputs will be visible
            panel_graphInputs.setVisible(true);
            
            // Update the the file test field so that users know which file is
            // the current file.
            textField_graphFile.setText(file.getName());
            
            // Load the data table with all data
            table_dataTable = new JTable(runData, columnHeaders);
            radioButton_data.doClick();
            
            // Set all of the Graph Control components to visible
            // Reset all of the checkboxes and comboBoxes
            // TODO: reset colorSelections
            for (int i=0; i<lineSelections.length; i++) {
                lineSelections[i].setVisible(true);
                lineSelections[i].setSelected(false);
                colorSelections[i].setVisible(true);
            }
            
            // hide unused controls (checkboxes and color selectors) 
            // based on the size of the column headers list.  
            int startIndex = columnHeaders.length;
            
            for (int i = startIndex; i < lineSelections.length; i++) {
                lineSelections[i].setVisible(false);
                colorSelections[i].setVisible(false);
            }
            
            // Clear the Graph panel of any graphs from the previous files
            buildGraph();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void buildGraph() {
        
        // When a checkbox is clicked, the method is called to graph all data
        // with a selected checkbox.  Loops through each item in the inputs array
        //  and checks to see if the checkbox is selected.  Then, gets the data from a column in  
        // the viewPort1Data 2D Array and converts it to a double[] array to be graphed.
        
        ArrayList<Line> lines = new ArrayList<>();
        
        for (int i=0; i<lineSelections.length; i++) {
            
            // Graphs the line if the boolean array value is true
            // Picts the color of the line based on index of the column
            if (lineSelections[i].isSelected()){
                
                double[] data = getLineData(i);
                Color color = colors[colorSelections[i].getSelectedIndex()];
              
                lines.add(new Line(data, color));
              
            }
            
        } 
     
        ((GraphPanel)graphPanel).setLines(lines);
    
    }

    private double[] getLineData(int i) {
        // Returns an array of double that contains all the values in the 
        // specified column
        double[] data = new double[runData.length];
        
        for (int row=0; row<runData.length; row++){           
            data[row] = runData[row][i];
        }
        
        return data;
        
    }

    private void initializeLineColors() {
        // These color values correspond to the colors of the graphed data lines.
        
        colors = new Color[13];
        colors[0] = Color.BLACK;
        colors[1] = Color.BLUE;
        colors[2] = Color.CYAN;
        colors[3] = Color.GREEN;
        colors[4] = Color.MAGENTA;
        colors[5] = Color.ORANGE;
        colors[6] = Color.PINK;
        colors[7] = Color.RED;
        colors[8] = Color.YELLOW;
        colors[9] = Color.LIGHT_GRAY;
        colors[10] = Color.BLUE;
        colors[11] = Color.CYAN;
        colors[12] = Color.GREEN;
        
    }
    
    //enable save menus
    private void enableSaveMenu(){
        menuItem_save.setEnabled(true);
        //menuItem_saveAs.setEnabled(true);
    }
    //disable save menus
    private void disableSaveMenu(){
        menuItem_save.setEnabled(false);
        //menuItem_saveAs.setEnabled(false);
    }

    private void initializeLineSelectors() {
        lineSelections = new JCheckBox[13];
        lineSelections[0] = new JCheckBox();
        lineSelections[1] = jCheckBox1;
        lineSelections[2] = jCheckBox2;
        lineSelections[3] = jCheckBox3;
        lineSelections[4] = jCheckBox4;
        lineSelections[5] = jCheckBox5;
        lineSelections[6] = jCheckBox6;
        lineSelections[7] = jCheckBox7;
        lineSelections[8] = jCheckBox8;
        lineSelections[9] = jCheckBox9;
        lineSelections[10] = jCheckBox10;
        lineSelections[11] = jCheckBox11;
        lineSelections[12] = jCheckBox12;
    }

    private void initializeColorSelectors() {
        colorSelections = new JComboBox[13];
        colorSelections[0] = new JComboBox();
        colorSelections[1] = jComboBox1;
        colorSelections[2] = jComboBox2; 
        colorSelections[3] = jComboBox3; 
        colorSelections[4] = jComboBox4; 
        colorSelections[5] = jComboBox5; 
        colorSelections[6] = jComboBox6; 
        colorSelections[7] = jComboBox7; 
        colorSelections[8] = jComboBox8;
        colorSelections[9] = jComboBox9;
        colorSelections[10] = jComboBox10;
        colorSelections[11] = jComboBox11;
        colorSelections[12] = jComboBox12;
    }
}
